name: ğŸ•’ Close Stale Issues/PRs Workflow

on:
  # Run the workflow every day
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  mark-inactivity:
    name: â³ Mark Issues/PRs without Activity
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Mark Issues/PRs without Activity
        # Close Stale Issues and PRs
        # https://github.com/marketplace/actions/close-stale-issues
        uses: actions/stale@v9.1.0
        with:
          repo-token: ${{ github.token }}
          days-before-stale: 183
          days-before-close: 7
          operations-per-run: 30
          remove-stale-when-updated: true
          enable-statistics: true
          stale-issue-message: >
            â³ This issue has been inactive for 6 months. If it's still relevant, drop a comment below to keep it open.
            Otherwise, it will be auto-closed in 7 days.
          stale-pr-message: >
            â³ This PR has been inactive for 6 months. If it's still relevant, update it or remove the stale label.
            Otherwise, it will be auto-closed in 7 days.
          close-issue-message: >
            ğŸ”’ This issue was auto-closed due to inactivity for over 6 months.
          close-pr-message: >
            ğŸ”’ This PR was auto-closed due to inactivity for over 6 months.
          stale-issue-label: 'âš°ï¸ Stale'
          close-issue-label: 'ğŸ•¸ï¸ Inactive'
          stale-pr-label: 'âš°ï¸ Stale'
          close-pr-label: 'ğŸ•¸ï¸ Inactive'
          exempt-issue-labels: 'ğŸ“Œ Keep Open'
          exempt-pr-labels: 'ğŸ“Œ Keep Open'

  await-user-response:
    name: âš ï¸ Mark Issues/PRs Awaiting User Response
    needs: [mark-inactivity]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Mark Issues/PRs Awaiting User Response
        # Close Stale Issues and PRs
        # https://github.com/marketplace/actions/close-stale-issues
        uses: actions/stale@v9.1.0
        with:
          repo-token: ${{ github.token }}
          days-before-stale: 7
          days-before-close: 7
          operations-per-run: 30
          remove-stale-when-updated: true
          stale-issue-message: >
            âš ï¸ Hey! We need some more info to move forward with this issue.
            Please provide the requested details in the next few days to keep this ticket open.
          close-issue-message: >
            ğŸ”’ This issue was auto-closed due to no response from user.
          only-labels: 'ğŸš Awaiting User Response'
          labels-to-remove-when-unstale: 'ğŸš Awaiting User Response'
          stale-issue-label: 'ğŸ›‘ No Response'
          close-issue-label: 'ğŸ•¸ï¸ Inactive'
          exempt-issue-labels: 'ğŸš§ Alternative Exists'

  alternative-exists:
    name: ğŸ”„ Mark Issues with Alternative Exists
    needs: [mark-inactivity, await-user-response]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Mark Issues with Alternative Exists
        # Close Stale Issues and PRs
        # https://github.com/marketplace/actions/close-stale-issues
        uses: actions/stale@v9.1.0
        with:
          repo-token: ${{ github.token }}
          days-before-stale: 7
          days-before-close: 7
          operations-per-run: 30
          remove-stale-when-updated: true
          stale-issue-message: >
            ğŸ”„ An alternative solution has been provided for this issue.
            Did this solve your problem? If so, we'll go ahead and close it.
            If you still need help, drop a comment within the next 7 days to keep this open.
          close-issue-message: >
            âœ… Closing this issue due to no confirmation on the alternative solution.
          only-labels: 'ğŸš§ Alternative Exists'
          stale-issue-label: 'ğŸš Awaiting User Response'
          close-issue-label: 'ğŸ•¸ï¸ Inactive'
          exempt-issue-labels: 'ğŸ“Œ Keep Open'
